# Generated by Django 3.2.3 on 2022-02-27 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220221_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='isMain',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.product'),
        ),
    ]
